export type InconfortThermique = {
  NA5AZ_sum: number | null;
  NA5BE_sum: number | null;
  NA5FZ_sum: number | null;
  NA5GU_sum: number | null;
  NA5OQ_sum: number | null;
  P20_POP80P: number | null;
  P20_POP80P_PSEUL: number | null;
  // P20_POP80P_PERCENT: number | null;
  age_bati_19_45: number | null;
  age_bati_46_90: number | null;
  age_bati_91_05: number | null;
  age_bati_post06: number | null;
  age_bati_pre_19: number | null;
  clc_1_artificialise: number | null;
  clc_2_agricole: number | null;
  clc_3_foret_semiNaturel: number | null;
  clc_4_humide: number | null;
  clc_5_eau: number | null;
  code_geographique: string;
  densite_bati: number | null;
  departement: string;
  libelle_departement: string;
  epci: string;
  index: bigint;
  libelle_epci: string;
  libelle_geographique: string;
  code_pnr: string | null;
  libelle_pnr: string | null;
  ept: string | null;
  libelle_petr: string | null;
  over_80_sum_1968: number | null;
  over_80_sum_1975: number | null;
  over_80_sum_1982: number | null;
  over_80_sum_1990: number | null;
  over_80_sum_1999: number | null;
  over_80_sum_2009: number | null;
  over_80_sum_2014: number | null;
  over_80_sum_2020: number | null;
  precarite_logement: number | null;
  region: bigint;
  s_geom_cstr_bati: number | null;
  superf_choro: number | null;
  tee_log: number | null;
  tee_mob: number | null;
  to_80_sum_1968: number | null;
  to_80_sum_1975: number | null;
  to_80_sum_1982: number | null;
  to_80_sum_1990: number | null;
  to_80_sum_1999: number | null;
  to_80_sum_2009: number | null;
  to_80_sum_2014: number | null;
  to_80_sum_2020: number | null;
  under_4_sum_1968: number | null;
  under_4_sum_1975: number | null;
  under_4_sum_1982: number | null;
  under_4_sum_1990: number | null;
  under_4_sum_1999: number | null;
  under_4_sum_2009: number | null;
  under_4_sum_2014: number | null;
  under_4_sum_2020: number | null;
};

export type ConfortThermique = {
  index: number;
  code_geographique: string;
  epci: string;
  libelle_epci: string;
  libelle_geographique: string;
  departement: string;
  libelle_departement: string;
  region: number;
  libelle_petr: string | null;
  code_pnr: string | null;
  libelle_pnr: string | null;
  ept: string | null;
  age_bati_19_45: number | null;
  age_bati_46_90: number | null;
  age_bati_91_05: number | null;
  age_bati_post06: number | null;
  age_bati_pre_19: number | null;
  under_4_sum_1968: number | null;
  under_4_sum_1975: number | null;
  under_4_sum_1982: number | null;
  under_4_sum_1990: number | null;
  under_4_sum_1999: number | null;
  under_4_sum_2006: number | null;
  under_4_sum_2011: number | null;
  under_4_sum_2016: number | null;
  under_4_sum_2022: number | null;
  '4_to_75_sum_1968': number | null;
  '4_to_75_sum_1975': number | null;
  '4_to_75_sum_1982': number | null;
  '4_to_75_sum_1990': number | null;
  '4_to_75_sum_1999': number | null;
  '4_to_75_sum_2006': number | null;
  '4_to_75_sum_2011': number | null;
  '4_to_75_sum_2016': number | null;
  '4_to_75_sum_2022': number | null;
  over_75_sum_1968: number | null;
  over_75_sum_1975: number | null;
  over_75_sum_1982: number | null;
  over_75_sum_1990: number | null;
  over_75_sum_1999: number | null;
  over_75_sum_2006: number | null;
  over_75_sum_2011: number | null;
  over_75_sum_2016: number | null;
  over_75_sum_2022: number | null;
  tee_log: number | null;
  tee_mob: number | null;
  precarite_logement: number | null;
  NA5AZ_sum: number | null;
  NA5BE_sum: number | null;
  NA5FZ_sum: number | null;
  NA5GU_sum: number | null;
  NA5OQ_sum: number | null;
  clc_1_artificialise: number | null;
  clc_2_agricole: number | null;
  clc_3_foret_semiNaturel: number | null;
  clc_4_humide: number | null;
  clc_5_eau: number | null;
  superf_choro: number | null;
};

export type Biodiversite = {
  type_touristique: string | null;
  code_geographique: string | null;
  departement: string | null;
  epci: string | null;
  index: number | null;
  libelle_epci: string | null;
  libelle_geographique: string | null;
  region: number | null;
};

export type GestionRisques = {
  lib_risque_jo: string;
  dat_pub_arrete: string;
  code_geographique: string;
  departement: string;
  epci: string;
  index: number;
  libelle_epci: string;
  libelle_geographique: string;
  region: number;
};

export type ArreteCatNat = {
  lib_risque_jo: string;
  dat_deb: string;
  dat_fin: string;
  dat_pub_arrete: string;
  code_geographique: string;
  departement: string;
  libelle_departement: string;
  epci: string;
  index: number;
  libelle_epci: string;
  libelle_geographique: string;
  region: number;
  ept: string | null;
  libelle_petr: string | null;
  code_pnr: string | null;
  libelle_pnr: string | null;
};

export type Secheresses = {
  index: number;
  code_geographique: string;
  departement: string;
  libelle_departement: string;
  epci: string;
  libelle_epci: string;
  libelle_geographique: string;
  region: number;
  ept: string | null;
  libelle_petr: string | null;
  code_pnr: string | null;
  libelle_pnr: string | null;
  restrictions_2013: string | null;
  restrictions_2014: string | null;
  restrictions_2015: string | null;
  restrictions_2016: string | null;
  restrictions_2017: string | null;
  restrictions_2018: string | null;
  restrictions_2019: string | null;
  restrictions_2020: string | null;
  restrictions_2021: string | null;
  restrictions_2022: string | null;
  restrictions_2023: string | null;
  restrictions_2024: string | null;
};

type RestrictionArrete = {
  dat_deb: string;
  dat_fin: string;
};

type RestrictionUsage = {
  nom: string;
  theme: string | null;
  part: number;
  entr: number;
  coll: number;
  expl: number;
  eso: number;
  esu: number;
  aep: number;
};

type RestrictionZas = {
  code: string;
  type: string;
  grav: number;
  pct: number;
};

export type RestrictionData = {
  arrete: RestrictionArrete;
  usage: RestrictionUsage;
  zas: RestrictionZas;
};

export type SecheressesParsed = Omit<Secheresses, `restrictions_${number}`> & {
  [key: `restrictions_${number}`]: RestrictionData[] | null;
};

export type RessourcesEau = {
  LIBELLE_SOUS_CHAMP: string;
  SOUS_CHAMP: string;
  code_geographique: string;
  departement: string;
  libelle_departement: string;
  epci: string;
  index: number;
  libelle_epci: string;
  libelle_geographique: string;
  ept: string | null;
  libelle_petr: string | null;
  code_pnr: string | null;
  libelle_pnr: string | null;
  region: number;
  A2008: number;
  A2009: number;
  A2010: number;
  A2011: number;
  A2012: number;
  A2013: number;
  A2014: number;
  A2015: number;
  A2016: number;
  A2017: number;
  A2018: number;
  A2019: number;
  A2020: number;
};

export type PrelevementsEau = {
  libelle_sous_champ: string | null;
  sous_champ: string | null;
  code_geographique: string;
  departement: string;
  libelle_departement: string;
  epci: string;
  index: number;
  libelle_epci: string;
  libelle_geographique: string;
  ept: string | null;
  libelle_petr: string | null;
  code_pnr: string | null;
  libelle_pnr: string | null;
  region: number;
  A2008: string | null;
  A2009: string | null;
  A2010: string | null;
  A2011: string | null;
  A2012: string | null;
  A2013: string | null;
  A2014: string | null;
  A2015: string | null;
  A2016: string | null;
  A2017: string | null;
  A2018: string | null;
  A2019: string | null;
  A2020: string | null;
};

export type PrelevementsEauModel = {
  index: number;
  code_geographique: string;
  libelle_geographique: string;
  epci: string;
  libelle_epci: string;
  departement: string;
  libelle_departement: string;
  region: number;
  ept: string | null;
  libelle_petr: string | null;
  code_pnr: string | null;
  libelle_pnr: string | null;
  annee_2017_aep: number;
  annee_2017_bar: number;
  annee_2017_can: number;
  annee_2017_ene: number;
  annee_2017_exo: number;
  annee_2017_ind: number;
  annee_2017_irr: number;
  annee_2018_aep: number;
  annee_2018_bar: number;
  annee_2018_can: number;
  annee_2018_ene: number;
  annee_2018_exo: number;
  annee_2018_ind: number;
  annee_2018_irr: number;
  annee_2019_aep: number;
  annee_2019_bar: number;
  annee_2019_can: number;
  annee_2019_ene: number;
  annee_2019_exo: number;
  annee_2019_ind: number;
  annee_2019_irr: number;
  annee_2020_aep: number;
  annee_2020_bar: number;
  annee_2020_can: number;
  annee_2020_ene: number;
  annee_2020_exo: number;
  annee_2020_ind: number;
  annee_2020_irr: number;
  annee_2021_aep: number;
  annee_2021_bar: number;
  annee_2021_can: number;
  annee_2021_ene: number;
  annee_2021_exo: number;
  annee_2021_ind: number;
  annee_2021_irr: number;
  annee_2022_aep: number;
  annee_2022_bar: number;
  annee_2022_can: number;
  annee_2022_ene: number;
  annee_2022_ind: number;
  annee_2022_irr: number;
  annee_2023_aep: number;
  annee_2023_bar: number;
  annee_2023_can: number;
  annee_2023_ene: number;
  annee_2023_exo: number;
  annee_2023_ind: number;
  annee_2023_irr: number;
};

export type PrelevementsEauParsed = {
  libelle_sous_champ: string | null;
  sous_champ: string | null;
  code_geographique: string;
  departement: string;
  libelle_departement: string;
  epci: string;
  index: number;
  libelle_epci: string;
  libelle_geographique: string;
  ept: string | null;
  libelle_petr: string | null;
  code_pnr: string | null;
  libelle_pnr: string | null;
  region: number;
  A2008: number;
  A2009: number;
  A2010: number;
  A2011: number;
  A2012: number;
  A2013: number;
  A2014: number;
  A2015: number;
  A2016: number;
  A2017: number;
  A2018: number;
  A2019: number;
  A2020: number;
};

export type AgricultureBio = {
  index: number;
  epci: string;
  libelle_epci: string;
  VARIABLE: string;
  LIBELLE_SOUS_CHAMP: string | null;
  surface_2023: number;
  surface_2022: number;
  surface_2021: number;
  surface_2020: number;
  surface_2019: number;
  surface_2018: number;
  surface_2017: number;
  surface_2016: number;
  surface_2015: number;
  surface_2014: number;
  surface_2013: number;
  surface_2012: number;
  surface_2011: number;
  surface_2010: number;
  surface_2009: number;
  surface_2008: number;
  nombre_2023: number;
  nombre_2022: number;
  nombre_2021: number;
  nombre_2020: number;
  nombre_2019: number;
  nombre_2018: number;
  nombre_2017: number;
  nombre_2016: number;
  nombre_2015: number;
  nombre_2014: number;
  nombre_2013: number;
  nombre_2012: number;
  nombre_2011: number;
  nombre_2010: number;
  nombre_2009: number;
  nombre_2008: number;
};

export type CollectivitesSearchbar = {
  code_geographique: string | null;
  coordinates: string | null;
  epci: string | null;
  libelle_geographique: string | null;
  libelle_epci: string | null;
  search_libelle: string;
  search_code: string | null;
  departement: string | null;
  region: string | null;
  ept: string | null;
  libelle_petr: string | null;
  code_pnr: string | null;
  libelle_pnr: string | null;
  libelle_departement: string | null;
};

export type CarteCommunes = {
  code_geographique: string;
  coordinates: string;
  epci: string;
  geometry: string;
  libelle_geographique: string;
  libelle_epci: string;
  departement: string;
  libelle_departement: string;
  region: number;
  ept: string;
  libelle_petr: string;
  code_pnr: string;
  libelle_pnr: string;
  precarite_logement?: number;
  catnat?: object;
  naf?: number | null;
  surface: number;
  surfacesIrriguees?: number;
  incendiesForet?: number;
};

export type CarteCommunesView = {
  code_geographique: string | null;
  coordinates: string | null;
  densite_bati?: number | null;
  epci: string | null;
  geometry: string | null;
  libelle_geographique: string | null;
  libelle_epci: string | null;
  departement: string | null;
  libelle_departement?: string | null;
  ept: string | null;
  libelle_petr: string | null;
  code_pnr: string | null;
  libelle_pnr: string | null;
  precarite_logement?: number | null;
  catnat?: object | null;
  naf?: number | null;
  surface: number | null;
  surfacesIrriguees?: number | null;
  incendiesForet?: number | null;
};

export type EpciContours = {
  epci_code: string;
  geometry: string;
  pk: number;
};

export type CLC = {
  centroid: string;
  geometry: string;
  label3: string;
  legend: string;
  pk: number;
  shape_length: number;
};

export type CLCTerritoires = {
  centroid: string;
  geometry: string;
  legend: string;
  pk: number;
  code_geographique: string;
  libelle_geographique: string;
  epci: string;
  libelle_epci: string;
  departement: string;
  libelle_departement: string;
  ept: string | null;
  libelle_petr: string | null;
  code_pnr: string | null;
  libelle_pnr: string | null;
};

export type ErosionCotiere = {
  pk: number;
  taux: number;
  duree: number;
  tdc_ancien: number;
  tdc_rec: number;
  geometry: string;
};

export type DataGrandAge = {
  P20_POP80P?: number;
  P20_POP80P_PSEUL?: number;
  code_geographique: string;
  epci: string;
  libelle_epci: string;
  libelle_geographique: string;
  over_80_sum_1968?: number;
  over_80_sum_1975?: number;
  over_80_sum_1982?: number;
  over_80_sum_1990?: number;
  over_80_sum_1999?: number;
  over_80_sum_2009?: number;
  over_80_sum_2014?: number;
  over_80_sum_2020?: number;
  to_80_sum_1968?: number;
  to_80_sum_1975?: number;
  to_80_sum_1982?: number;
  to_80_sum_1990?: number;
  to_80_sum_1999?: number;
  to_80_sum_2009?: number;
  to_80_sum_2014?: number;
  to_80_sum_2020?: number;
  under_4_sum_1968?: number;
  under_4_sum_1975?: number;
  under_4_sum_1982?: number;
  under_4_sum_1990?: number;
  under_4_sum_1999?: number;
  under_4_sum_2009?: number;
  under_4_sum_2014?: number;
  under_4_sum_2020?: number;
};

export type SurfacesProtegeesByCol = {
  index: number;
  code_geographique: string;
  PNC: string | null;
  RAMSAR: string | null;
  PNR: string | null;
  PNP: string | null;
  FOR_PRO: string | null;
  ZZZ: string | null;
  ZNIEFF2: string | null;
  ZNIEFF1: string | null;
  RNR: string | null;
  TOU_PRO: string | null;
  NATURA: string | null;
  ZPS: string | null;
  SIC: string | null;
  CELRL: string | null;
  BIO: string | null;
  APB: string | null;
  RN: string | null;
  RBFD: string | null;
  RNCFS: string | null;
  libelle_geographique: string;
  epci: string;
  libelle_epci: string;
  departement: string;
  region: number;
};

export type ConsommationNAF = {
  index: number;
  code_geographique: string;
  libelle_geographique: string;
  epci: string;
  libelle_epci: string;
  departement: string;
  libelle_departement: string;
  region: number;
  ept: string | null;
  libelle_petr: string | null;
  code_pnr: string | null;
  libelle_pnr: string | null;
  naf09art10: number | null;
  art09act10: number | null;
  art09hab10: number | null;
  art09mix10: number | null;
  art09rou10: number | null;
  art09fer10: number | null;
  art09inc10: number | null;
  naf10art11: number | null;
  art10act11: number | null;
  art10hab11: number | null;
  art10mix11: number | null;
  art10rou11: number | null;
  art10fer11: number | null;
  naf11art12: number | null;
  art11act12: number | null;
  art11hab12: number | null;
  art11mix12: number | null;
  art11rou12: number | null;
  art11fer12: number | null;
  art11inc12: number | null;
  naf12art13: number | null;
  art12act13: number | null;
  art12hab13: number | null;
  art12mix13: number | null;
  art12rou13: number | null;
  art12fer13: number | null;
  art12inc13: number | null;
  naf13art14: number | null;
  art13act14: number | null;
  art13hab14: number | null;
  art13mix14: number | null;
  art13rou14: number | null;
  art13fer14: number | null;
  art13inc14: number | null;
  naf14art15: number | null;
  art14act15: number | null;
  art14hab15: number | null;
  art14mix15: number | null;
  art14rou15: number | null;
  art14fer15: number | null;
  art14inc15: number | null;
  naf15art16: number | null;
  art15act16: number | null;
  art15hab16: number | null;
  art15mix16: number | null;
  art15rou16: number | null;
  art15fer16: number | null;
  art15inc16: number | null;
  naf16art17: number | null;
  art16act17: number | null;
  art16hab17: number | null;
  art16mix17: number | null;
  art16rou17: number | null;
  art16fer17: number | null;
  art16inc17: number | null;
  naf17art18: number | null;
  art17act18: number | null;
  art17hab18: number | null;
  art17mix18: number | null;
  art17rou18: number | null;
  art17fer18: number | null;
  art17inc18: number | null;
  naf18art19: number | null;
  art18act19: number | null;
  art18hab19: number | null;
  art18mix19: number | null;
  art18rou19: number | null;
  art18fer19: number | null;
  art18inc19: number | null;
  naf19art20: number | null;
  art19act20: number | null;
  art19hab20: number | null;
  art19mix20: number | null;
  art19rou20: number | null;
  art19fer20: number | null;
  art19inc20: number | null;
  naf20art21: number | null;
  art20act21: number | null;
  art20hab21: number | null;
  art20mix21: number | null;
  art20rou21: number | null;
  art20fer21: number | null;
  art20inc21: number | null;
  naf21art22: number | null;
  art21act22: number | null;
  art21hab22: number | null;
  art21mix22: number | null;
  art21rou22: number | null;
  art21fer22: number | null;
  art21inc22: number | null;
  naf22art23: number | null;
  art22act23: number | null;
  art22hab23: number | null;
  art22mix23: number | null;
  art22rou23: number | null;
  art22fer23: number | null;
  art22inc23: number | null;
  naf09art23: number | null;
  art09act23: number | null;
  art09hab23: number | null;
  art09mix23: number | null;
  art09inc23: number | null;
  art09rou23: number | null;
  art09fer23: number | null;
  artcom0923: number | null;
};

export type EtatCoursDeau = {
  pk: number;
  name: string;
  longueur: number;
  etateco: string | null;
  geometry: string;
};

export type AOT40 = {
  index: number;
  nom_site: string;
  type_d_implantation: string;
  valeur_brute: number;
  Latitude: number;
  Longitude: number;
};

export type O3 = {
  index: number;
  nom_site: string;
  valeur: number;
  latitude: number;
  longitude: number;
};

export type Agriculture = {
  index: number;
  code_geographique: string;
  libelle_geographique: string;
  epci: string;
  libelle_epci: string;
  departement: string;
  libelle_departement: string;
  region: number;
  ept: string | null;
  libelle_petr: string | null;
  code_pnr: string | null;
  libelle_pnr: string | null;
  part_irr_SAU_2020: number | null;
  otex_12_postes: string;
};

export type ExportCoursDeau = {
  index: number;
  code_geographique: string;
  libelle_geographique: string;
  epci: string;
  libelle_epci: string;
  departement: string;
  libelle_departement: string;
  region: number;
  ept: string | null;
  libelle_petr: string | null;
  code_pnr: string | null;
  libelle_pnr: string | null;
  cours_d_eau: string;
  etat_ecologique: string | null;
  longueur: number;
};

export type IncendiesForet = {
  index: number;
  code_geographique: string;
  libelle_geographique: string;
  epci: string;
  libelle_epci: string;
  departement: string;
  libelle_departement: string;
  region: number;
  ept: string | null;
  libelle_petr: string | null;
  code_pnr: string | null;
  libelle_pnr: string | null;
  nature: string | null;
  annee: number;
  surface_parcourue: number;
  surface_foret: number | null;
  surface_maquis_garrigues: number | null;
  autres_surfaces_naturelles_hors_foret: number | null;
  surfaces_agricoles: number | null;
  surfaces_non_boisees: number | null;
  surfaces_non_boisees_artificialisees: number | null;
  surfaces_non_boisees_naturelles: number | null;
  surface_autres_terres_boisees: number | null;
  autres_surfaces: number | null;
};

export type RGACarte = {
  pk: number;
  alea: string;
  code_geographique: string;
  geometry: string;
};

export type RGAdb = {
  index: number;
  code_geographique: string;
  libelle_geographique: string;
  epci: string;
  libelle_epci: string;
  departement: string;
  libelle_departement: string;
  region: number;
  ept: string | null;
  libelle_petr: string | null;
  code_pnr: string | null;
  libelle_pnr: string | null;
  nb_logement: number;
  nb_logement_alea_moyen_fort: number;
  nb_logement_alea_faible: number;
  nb_logement_sans_alea: number;
  nb_logement_alea_moyen_fort_avant_1920: number;
  nb_logement_alea_moyen_fort_1920_1945: number;
  nb_logement_alea_moyen_fort_1945_1975: number;
  nb_logement_alea_moyen_fort_apres_1975: number;
  nb_logement_alea_faible_avant_1920: number;
  nb_logement_alea_faible_1920_1945: number;
  nb_logement_alea_faible_1945_1975: number;
  nb_logement_alea_faible_apres_1975: number;
  surface_commune: number;
  surface_alea_faible_commune: number;
  surface_alea_moyen_fort_commune: number;
  part_logement_alea_moyen_fort_avant_1920: number;
  part_logement_alea_moyen_fort_1920_1945: number;
  part_logement_alea_moyen_fort_1945_1975: number;
  part_logement_alea_moyen_fort_apres_1975: number;
  part_logement_alea_faible_avant_1920: number;
  part_logement_alea_faible_1920_1945: number;
  part_logement_alea_faible_1945_1975: number;
  part_logement_alea_faible_apres_1975: number;
  part_alea_faible_commune: number;
  part_alea_moyen_fort_commune: number;
};

export type SurfacesAgricolesModel = {
  index: number;
  epci: string;
  exploitation_sau: number | null;
  exploitation_sau_terres_arables: number | null;
  exploitation_sau_terres_arables_cereales: number | null;
  exploitation_sau_terres_arables_oleagineux: number | null;
  exploitation_sau_terres_arables_fourrageres: number | null;
  exploitation_sau_terres_arables_tubercules: number | null;
  exploitation_sau_terres_arables_legumes_melons_fraises: number | null;
  exploitation_sau_terres_arables_fleurs: number | null;
  exploitation_sau_terres_arables_autres: number | null;
  exploitation_sau_cultures_permanentes: number | null;
  exploitation_sau_cultures_permanentes_vigne: number | null;
  exploitation_sau_cultures_permanentes_fruits: number | null;
  exploitation_sau_cultures_permanentes_autres: number | null;
  exploitation_sau_herbe: number | null;
  exploitation_sau_herbe_prairies_productives: number | null;
  exploitation_sau_herbe_prairies_peu_productives: number | null;
  exploitation_sau_herbe_subventions: number | null;
  exploitation_sau_herbe_bois_patures: number | null;
  exploitation_sau_jardins: number | null;
  superficie_sau: number | null;
  superficie_sau_terres_arables: number | null;
  superficie_sau_terres_arables_cereales: number | null;
  superficie_sau_terres_arables_oleagineux: number | null;
  superficie_sau_terres_arables_fourrageres: number | null;
  superficie_sau_terres_arables_tubercules: number | null;
  superficie_sau_terres_arables_legumes_melons_fraises: number | null;
  superficie_sau_terres_arables_fleurs: number | null;
  superficie_sau_terres_arables_autres: number | null;
  superficie_sau_cultures_permanentes: number | null;
  superficie_sau_cultures_permanentes_vigne: number | null;
  superficie_sau_cultures_permanentes_fruits: number | null;
  superficie_sau_cultures_permanentes_autres: number | null;
  superficie_sau_herbe: number | null;
  superficie_sau_herbe_prairies_productives: number | null;
  superficie_sau_herbe_prairies_peu_productives: number | null;
  superficie_sau_herbe_subventions: number | null;
  superficie_sau_herbe_bois_patures: number | null;
  superficie_sau_jardins: number | null;
};

export type Patch4 = {
  index: number;
  code_geographique: string;
  libelle_geographique: string;
  epci: string;
  libelle_epci: string;
  departement: string;
  region: number;
  ept: string | null;
  libelle_petr: string | null;
  code_pnr: string | null;
  libelle_pnr: string | null;
  niveaux_marins: number | null;
  feux_foret: number;
  secheresse_sols: number;
  fortes_precipitations: number;
  fortes_chaleurs: number;
};

export type LczCouverture = {
  index: number;
  code_geographique: string;
  libelle_geographique: string;
  epci: string;
  libelle_epci: string;
  departement: string;
  libelle_departement: string;
  region: number;
  ept: string | null;
  libelle_petr: string | null;
  code_pnr: string | null;
  libelle_pnr: string | null;
  couverture_lcz: number | null;
};

export type AtlasBiodiversiteModel = {
  index: number;
  code_geographique: string;
  libelle_geographique: string;
  epci: string;
  libelle_epci: string;
  departement: string;
  libelle_departement: string;
  region: number;
  ept: string | null;
  libelle_petr: string | null;
  code_pnr: string | null;
  libelle_pnr: string | null;
  nom: string | null;
  structure_porteuse: string | null;
  type_de_structure_porteuse: string | null;
  annee_debut: number | null;
  avancement: string | null;
};

export type TableCommuneModel = {
  index: number;
  code_geographique: string;
  libelle_geographique: string;
  epci: string;
  libelle_epci: string;
  departement: string;
  libelle_departement: string;
  region: number;
  ept: string | null;
  libelle_petr: string | null;
  code_pnr: string | null;
  libelle_pnr: string | null;
  type_touristique: string | null;
  atlas_biodiversite_nom: string | null;
  atlas_biodiversite_annee_debut: number | null;
  atlas_biodiversite_avancement: string | null;
  otex_12_postes: string | null;
  part_irr_sau_2020: string | null;
  agriculture_part_over_55: string | null;
  couverture_lcz: string | null;
  aires_appellations_controlees_nom: string[] | null;
  aires_appellations_controlees_signe: string[] | null;
};

export type DebroussaillementModel = {
  pk: number;
  code_geographique: string;
  libelle_geographique: string;
  epci: string;
  libelle_epci: string;
  departement: string;
  libelle_departement: string;
  region: number;
  ept: string | null;
  libelle_petr: string | null;
  code_pnr: string | null;
  libelle_pnr: string | null;
  geometry: string;
};

export type SecheressesPasseesModel = {
  index: number;
  code_geographique: string;
  libelle_geographique: string | null;
  epci: string | null;
  libelle_epci: string | null;
  departement: string | null;
  libelle_departement: string | null;
  region: number | null;
  ept: string | null;
  libelle_petr: string | null;
  code_pnr: string | null;
  libelle_pnr: string | null;
  restrictions: string | null;
};

export type QualiteSitesBaignadeModel = {
  index: number;
  code_geographique: string;
  libelle_geographique: string;
  epci: string;
  libelle_epci: string;
  departement: string;
  libelle_departement: string;
  region: number;
  nom_site: string;
  latitude: number;
  longitude: number;
  type_eau_norm: string;
  statut_donnees: string;
  qualite: string;
};

export type ArboviroseModel = {
  index: number;
  annee: string;
  departement: string;
  nb_cas_importes: number;
  nb_cas_autochtones: number;
};
